version: '3.2'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 443:443
        restart: always

    codescene:
        depends_on:
            - reverseproxy
        image: empear/ubuntu-onprem:latest
        restart: always
        volumes:
          - "./docker-codescene/resources:/resources"
